apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ypul1ubeb-python 
  janus-idp.io/tekton: ypul1ubeb-python
  backstage.io/kubernetes-id: ypul1ubeb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ypul1ubeb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml